version: '3.8'

services:
    web:
        image: ml-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/app
        restart: always